version: '3.4'

services:
  employeeservice:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: employeeservice
    build:
      context: ./EmployeeService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  payrollservice:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: payrollservice
    build:
      context: ./PayrollService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
